import type { Metadata } from "next";
import localFont from "next/font/local";
import { Montserrat, Poppins, Nunito } from "next/font/google";

import { Header } from "@/components/Header";
import "./globals.css";
import ViewCanvas from "@/components/ViewCanvas";
import Footer from "@/components/Footer";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const avalors = localFont({
  src: "./fonts/Avalors-Personal-Use-Only.woff",
  variable: "--font-avalors",
  display: "swap",
});

const meadow = localFont({
  src: "./fonts/Meadow-Free.woff",
  variable: "--font-meadow",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${montserrat.variable} ${poppins.variable} ${meadow.variable} ${avalors.variable} font-avalors font-medium antialiased overflow-x-hidden bg-yellow-300`}
      >
        <Header />
        <main>
          {children}
          <ViewCanvas />
        </main>
        <Footer />
      </body>
    </html>
  );
}
