import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Montserrat, Poppins, Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const avalors = localFont({
  src: "./fonts/Avalors-Personal-Use-Only.woff",
  variable: "--font-avalors",
  display: "swap",
})

const meadow = localFont({
  src: "./fonts/Meadow-Free.woff",
  variable: "--font-meadow",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${montserrat.variable} ${poppins.variable} ${meadow.variable} ${avalors.variable} antialiased font-avalors font-medium`}
      >
        {children}
      </body>
    </html>
  );
}
